site_name: SpeciesInteractionNetworks.jl
repo_url: https://github.com/PoisotLab/SpeciesInteractionNetworks.jl
site_description: Analysis of Species Interaction Networks using Julia
site_author: Timothée Poisot

theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - toc.follow
    - toc.integrate
    - navigation.top
    - navigation.instant
    - navigation.tracking


extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - admonition
  - pymdownx.details
  - pymdownx.superfences

docs_dir: 'build'

nav:
  - Getting started:
    - Index: index.md
    - Building a network: getting_started/demonstration.md
    - Type system: getting_started/types.md
  - Micro:
    - Specificity: species_level/specificity.md
    - Centrality: species_level/centrality.md
  - Meso:
    - Paths: meso_level/paths.md
  - Macro:
    - Nestedness: community_level/nestedness.md
  - Meta:
    - Beta-diversity: meta_level/betadiversity.md
    - Set operations: meta_level/sets.md
  - Random:
    - Permutations: random_networks/permutations.md
    - Structural models: random_networks/structural.md
  - Appendix:
    - Bibliography: bibliography.md
    - Internals: internals.md