site_name: SpeciesInteractionNetworks.jl
repo_url: https://github.com/PoisotLab/SpeciesInteractionNetworks.jl
site_description: Analysis of Species Interaction Networks using Julia
site_author: Timothée Poisot

theme:
  name: material
  palette:
    scheme: default
    primary: white
    accent: indigo
  features:
    - navigation.tabs
    - toc.follow
    - toc.integrate
    - navigation.top
    - navigation.footer


extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - admonition
  - pymdownx.details
  - pymdownx.superfences

docs_dir: 'build'

nav:
  - Home: index.md
  - Getting started:
    - Building a network: getting_started/demonstration.md
    - Type system: getting_started/types.md
  - Species (micro) level measures:
    - Specificity: species_level/specificity.md
    - Centrality: species_level/centrality.md
  - Intermediate (meso) level measures:
    - Paths: meso_level/paths.md
  - Community (macro) level measures:
    - Nestedness: community_level/nestedness.md
  - Networks (meta) level measures:
    - Set operations: meta_level/sets.md
  - Random networks:
    - Permutations: random_networks/permutations.md
  - Bibliography: bibliography.md
  - Internals: internals.md